name: breast_cancer_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scikit-learn=1.0.2
  - pandas=1.3.5
  - pip=21.3.1
  - pip:
    - mlflow==2.3.2
    - dagshub
  - matplotlib
  - seaborn
  - joblib
  - prometheus_client
  - python-dotenv
