name: breast_cancer_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - joblib
  - prometheus_client
  - python-dotenv
  - pip
